name: webapp-wf-dev

on:
  push:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: devProject # Checkout to the root directory

      # Use Azure Login Service Connection
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'  # Reference the Service Connection secret

      # Deploy ARM template with environment variables
      - name: Deploy ARM Template
        id: arm
        uses: azure/arm-deploy@v1
        with:
          region: centralindia
          resourceGroupName: myappresource
